name: dropcode
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - bwa
  - samtools
  - fastp
  - bcftools
  - openjdk=11.0.2
  - pip
  - pip:
    - pandas
    - openpyxl
    - biopython
    - pyvcf